[package]
name = "respcheck"
version = "0.1.0"
authors = ["n01e0"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "*", features = [ "json" ]}
colored = "*"
